
export type SortDirection = 'asc' | 'desc';

export interface SortOption {
  property: 'date' | 'name' | 'color';
  direction: SortDirection;
}

export interface ClothingItemMetadata {
  description?: string;
  category: string;
  subcategory: string;
  color_primary: string;
  neckline?: string;
  sleeve_type?: string;
  vibe_tags: string[];
  seasons: string[];
}

export interface ClothingItem {
  id: string;
  imageDataUrl: string;
  metadata: ClothingItemMetadata;
  isAIGenerated?: boolean; // True if item was generated by AI (not from user's closet)
  aiGenerationPrompt?: string; // Original prompt used to generate this item
}

export interface MissingPieceSuggestion {
  item_name: string;
  reason: string;
}

export interface FitResult {
  top_id: string;
  bottom_id: string;
  shoes_id: string;
  explanation: string;
  missing_piece_suggestion?: MissingPieceSuggestion;
  aiGeneratedItems?: {
    top?: ClothingItem;
    bottom?: ClothingItem;
    shoes?: ClothingItem;
  }; // AI-generated items to fill missing pieces
}

export interface SavedOutfit {
  id: string;
  top_id: string;
  bottom_id: string;
  shoes_id: string;
  explanation: string;
}

export interface PackingListResult {
  packing_list: string[];
  outfit_suggestions: string;
}

export interface CommunityUser {
  id: string;
  name: string;
  username: string;
  avatarUrl: string;
  closet: ClothingItem[];
}

export interface WebSource {
  uri: string;
  title: string;
}

export interface GroundingChunk {
  web: WebSource;
}

export interface ColorPaletteAnalysis {
  dominant_colors: ColorInfo[];
  color_scheme: 'monochromatic' | 'complementary' | 'analogous' | 'triadic' | 'diverse';
  missing_colors: string[];
  versatility_score: number;
  recommendations: string;
}

export interface ColorInfo {
  name: string;
  hex: string;
  percentage: number;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
  outfitSuggestion?: {
    top_id: string;
    bottom_id: string;
    shoes_id: string;
    aiGeneratedItems?: {
      top?: ClothingItem;
      bottom?: ClothingItem;
      shoes?: ClothingItem;
    };
  };
}

export interface ChatState {
  messages: ChatMessage[];
  isTyping: boolean;
}

export interface ChatConversation {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
  preview?: string; // First user message for display
}

export interface WeatherData {
  temp: number;
  feels_like: number;
  temp_min: number;
  temp_max: number;
  condition: string;
  description: string;
  icon: string;
  city: string;
  country: string;
}

export interface WeatherOutfitResult {
  outfit: {
    top_id: string;
    bottom_id: string;
    shoes_id: string;
  };
  explanation: string;
  weather_context: string;
}

export interface OutfitSchedule {
  id: string;
  user_id: string;
  date: string; // ISO date format (YYYY-MM-DD)
  outfit_id: string;
  created_at?: string;
  updated_at?: string;
}

export interface ScheduledOutfitWithDetails extends OutfitSchedule {
  outfit: SavedOutfit;
}

export type LookbookTheme = 'office' | 'weekend' | 'date_night' | 'casual' | 'formal' | 'travel' | 'custom';

export interface LookbookOutfit {
  top_id: string;
  bottom_id: string;
  shoes_id: string;
  title: string; // e.g., "Look 1: Professional Power"
  description: string; // Short description of the vibe
}

export interface Lookbook {
  theme: string;
  outfits: LookbookOutfit[];
  theme_description: string;
}

export type ChallengeType = 'color' | 'style' | 'occasion' | 'seasonal' | 'creativity' | 'minimalist';
export type ChallengeDifficulty = 'easy' | 'medium' | 'hard';
export type ChallengeStatus = 'active' | 'completed' | 'skipped';

export interface StyleChallenge {
  id: string;
  user_id: string;
  type: ChallengeType;
  difficulty: ChallengeDifficulty;
  title: string;
  description: string;
  constraints: string[];
  required_items?: string[]; // Optional: specific item categories needed
  duration_days: number;
  points_reward: number;
  status: ChallengeStatus;
  created_at?: string;
  completed_at?: string;
  outfit_id?: string; // Reference to outfit created for challenge
}

export interface ChallengeOutfitSubmission {
  top_id: string;
  bottom_id: string;
  shoes_id: string;
  explanation: string;
  meets_constraints: boolean;
  creativity_score: number; // 0-10
  feedback: string;
}

export interface OutfitRating {
  id: string;
  outfit_id: string;
  rating: number; // 1-5 stars
  notes?: string;
  created_at?: string;
  updated_at?: string;
}

export interface RatingStats {
  average_rating: number;
  total_ratings: number;
  rating_distribution: Record<number, number>; // {1: 5, 2: 3, 3: 10, 4: 20, 5: 12}
  highest_rated_outfit?: SavedOutfit & { rating: number };
  lowest_rated_outfit?: SavedOutfit & { rating: number };
}

export interface OutfitWithRating extends SavedOutfit {
  rating?: OutfitRating;
}

// =====================================================
// Feature 13: AI Feedback Analyzer Types
// =====================================================

export interface PreferencePattern {
  attribute: string; // e.g., "color", "style", "occasion", "season"
  value: string; // e.g., "black", "casual", "work"
  frequency: number; // how often appears in high-rated outfits
  average_rating: number; // average rating when this attribute is present
}

export interface FeedbackInsights {
  satisfaction_score: number; // 0-100, overall satisfaction with wardrobe
  top_preferences: PreferencePattern[]; // what user loves (high ratings)
  least_favorites: PreferencePattern[]; // what user dislikes (low ratings)
  style_evolution: string; // narrative of how style preferences are evolving
  improvement_suggestions: string[]; // specific actionable suggestions
  shopping_recommendations: string[]; // items to buy based on preferences
  unused_potential: string[]; // existing items user should try more
}

export interface FeedbackAnalysisResult {
  insights: FeedbackInsights;
  analyzed_ratings_count: number;
  analyzed_outfits_count: number;
  date_range: {
    from: string;
    to: string;
  };
  confidence_level: 'low' | 'medium' | 'high'; // based on data quantity
}

export interface FeedbackPatternData {
  ratings: OutfitRating[];
  outfits: SavedOutfit[];
  closet: ClothingItem[];
}

// =====================================================
// Feature 14: Closet Gap Analysis Types
// =====================================================

export interface GapAnalysisItem {
  category: string; // e.g., "top", "bottom", "shoes"
  subcategory: string; // e.g., "white button-down shirt", "black dress pants"
  reason: string; // why this item would complete the wardrobe
  priority: 'essential' | 'recommended' | 'optional';
  occasions: string[]; // e.g., ["work", "formal events", "date night"]
  style_compatibility: number; // 0-10 score for how well it fits user's style
  color_suggestion: string; // recommended color
  alternatives?: string[]; // similar items user could get instead
}

export interface VersatilityScore {
  current_score: number; // 0-100
  potential_score: number; // 0-100 with suggested items
  bottleneck_categories: string[]; // categories limiting versatility
}

export interface ClosetGapAnalysisResult {
  missing_essentials: GapAnalysisItem[]; // must-have items
  nice_to_have: GapAnalysisItem[]; // recommended additions
  versatility_analysis: VersatilityScore;
  strengths: string[]; // what the closet does well
  weaknesses: string[]; // what's missing or limiting
  style_summary: string; // overall style profile of current closet
  shopping_budget_estimate: string; // rough estimate for missing essentials
  analyzed_items_count: number;
  confidence_level: 'low' | 'medium' | 'high'; // based on closet size
}

// =====================================================
// Feature 15: Brand & Price Recognition Types
// =====================================================

export interface BrandInfo {
  name: string; // e.g., "Nike", "Zara", "Gucci"
  confidence: number; // 0-100, how confident the AI is about the brand detection
  detected_from: 'logo' | 'label' | 'style_pattern' | 'mixed'; // where brand was identified
  country_origin?: string; // e.g., "USA", "Spain", "Italy"
  brand_tier: 'luxury' | 'premium' | 'mid-range' | 'budget' | 'unknown';
}

export interface PriceEstimate {
  currency: string; // e.g., "USD", "EUR", "ARS"
  min_price: number; // minimum estimated price
  max_price: number; // maximum estimated price
  average_price: number; // most likely price point
  confidence: number; // 0-100, confidence in price estimate
  factors: string[]; // factors affecting price (e.g., "brand reputation", "material quality", "condition")
}

export type AuthenticityStatus = 'original' | 'replica' | 'indeterminate';

export interface AuthenticityAssessment {
  status: AuthenticityStatus;
  confidence: number; // 0-100
  indicators: string[]; // visual cues that led to this assessment
  warnings?: string[]; // potential red flags if replica suspected
}

export interface BrandRecognitionResult {
  brand: BrandInfo;
  price_estimate: PriceEstimate;
  authenticity: AuthenticityAssessment;
  item_condition: 'new' | 'like_new' | 'good' | 'fair' | 'worn'; // detected condition
  resale_value_percentage: number; // 0-100, % of original price for resale
  market_insights: string; // brief market commentary (e.g., "This brand is currently trending")
  shopping_alternatives?: string[]; // similar brands at different price points
  analyzed_at: string; // ISO timestamp
}

// =====================================================
// Feature 16: Dupe Finder Types
// =====================================================

export interface DupeItem {
  title: string; // product name
  brand: string; // brand or seller
  price: number; // price in the detected currency
  currency: string; // e.g., "USD", "ARS"
  image_url?: string; // product image if available
  shop_url: string; // link to product page
  shop_name: string; // e.g., "SHEIN", "Amazon", "AliExpress"
  similarity_score: number; // 0-100, visual similarity to original item
  key_differences: string[]; // notable differences from original (e.g., "slightly different fabric texture", "color tone varies")
  savings_amount: number; // price difference from original (original_price - dupe_price)
  savings_percentage: number; // % saved compared to original
  estimated_quality: 'high' | 'medium' | 'low' | 'unknown'; // AI estimate based on price/brand
}

export interface VisualComparison {
  similarities: string[]; // what looks similar (e.g., "same silhouette", "matching neckline")
  differences: string[]; // what's different (e.g., "fabric looks cheaper", "stitching details vary")
  overall_match: number; // 0-100, overall visual similarity score
}

export interface SavingsCalculation {
  original_price: number;
  cheapest_dupe_price: number;
  max_savings: number;
  average_dupe_price: number;
  average_savings: number;
  currency: string;
}

export interface DupeFinderResult {
  original_item: {
    id: string;
    brand?: string; // from previous brand recognition if available
    estimated_price?: number; // from previous brand recognition if available
    category: string;
    subcategory: string;
  };
  dupes: DupeItem[];
  visual_comparison: VisualComparison;
  savings: SavingsCalculation;
  search_strategy: string; // brief explanation of how dupes were found
  confidence_level: 'low' | 'medium' | 'high'; // overall confidence in results
  analyzed_at: string; // ISO timestamp
}

// =====================================================
// Feature 17: Capsule Wardrobe Builder Types
// =====================================================

export type CapsuleTheme = 'work' | 'casual' | 'travel' | 'minimal' | 'seasonal' | 'custom';

export type CapsuleSize = 10 | 15 | 20 | 30;

export interface CapsuleItem {
  item_id: string; // reference to ClothingItem.id
  versatility_score: number; // 0-100, how many items it pairs with
  category: string; // top, bottom, shoes, etc.
  color_primary: string;
  style_match_score: number; // 0-100, how well it fits the capsule theme
  reasoning: string; // why this item was selected for the capsule
}

export interface CompatibilityPair {
  item1_id: string;
  item2_id: string;
  compatibility_score: number; // 0-100
  reasoning: string; // why they work together (or don't)
}

export interface CapsuleOutfitCombination {
  top_id?: string;
  bottom_id?: string;
  shoes_id?: string;
  outerwear_id?: string; // optional layer
  occasion: string; // e.g., "Work meeting", "Casual brunch", "Travel day"
  explanation: string; // why this combination works
}

export interface CapsuleWardrobe {
  id: string; // unique capsule ID
  name: string; // user-given or auto-generated name
  theme: CapsuleTheme;
  size: CapsuleSize;
  items: CapsuleItem[]; // selected items with metadata
  compatibility_matrix: CompatibilityPair[]; // all pairwise compatibility scores
  suggested_outfits: CapsuleOutfitCombination[]; // pre-generated outfit ideas
  total_combinations: number; // mathematical combinations possible
  color_palette: string[]; // dominant colors in the capsule
  missing_pieces?: string[]; // gaps in the capsule (optional items to add)
  season?: string; // if seasonal theme
  created_at: string; // ISO timestamp
  strategy_explanation: string; // how the capsule was built
}

// =====================================================
// Feature 18: Style DNA Profile Types
// =====================================================

export type StyleArchetype =
  | 'casual'
  | 'formal'
  | 'sporty'
  | 'bohemian'
  | 'minimalist'
  | 'edgy'
  | 'classic'
  | 'trendy'
  | 'romantic'
  | 'preppy';

export interface StyleArchetypeScore {
  archetype: StyleArchetype;
  percentage: number; // 0-100
  description: string;
  key_items: string[]; // item IDs that represent this archetype
}

export interface ColorProfile {
  dominant_colors: ColorInfo[]; // top colors in wardrobe
  color_temperature: 'warm' | 'cool' | 'neutral' | 'mixed';
  color_boldness: 'vibrant' | 'muted' | 'mixed'; // intensity of colors
  favorite_neutrals: string[]; // most used neutral colors
  accent_colors: string[]; // non-neutral colors used
}

export type SilhouetteType = 'oversized' | 'fitted' | 'structured' | 'flowy' | 'tailored' | 'relaxed';

export interface SilhouettePreference {
  type: SilhouetteType;
  percentage: number; // 0-100
  description: string;
}

export interface OccasionBreakdown {
  occasion: string; // e.g., "work", "casual", "formal", "athletic"
  percentage: number; // 0-100
  item_count: number;
  typical_items: string[]; // item IDs
}

export interface StylePersonalityTrait {
  trait: string; // e.g., "adventurous", "practical", "creative"
  score: number; // 0-10
  reasoning: string;
}

export interface CelebrityStyleMatch {
  name: string; // celebrity name
  match_percentage: number; // 0-100
  reasoning: string;
  shared_characteristics: string[]; // what they have in common
  image_url?: string; // optional celebrity reference image
}

export interface StyleEvolutionInsight {
  trend: string; // e.g., "increasingly minimalist", "adding more color"
  evidence: string; // what data supports this
  recommendation: string; // how to continue or adjust
}

export interface StyleDNAProfile {
  id: string;
  user_id?: string;
  archetypes: StyleArchetypeScore[]; // sorted by percentage desc
  primary_archetype: StyleArchetype; // dominant style
  secondary_archetype?: StyleArchetype; // second most dominant
  color_profile: ColorProfile;
  silhouette_preferences: SilhouettePreference[];
  occasion_breakdown: OccasionBreakdown[];
  personality_traits: StylePersonalityTrait[];
  celebrity_matches: CelebrityStyleMatch[]; // top 3-5 matches
  style_evolution_insights: StyleEvolutionInsight[];
  versatility_score: number; // 0-100, how versatile the wardrobe is
  uniqueness_score: number; // 0-100, how unique/distinctive the style is
  confidence_level: 'low' | 'medium' | 'high'; // based on wardrobe size
  analyzed_items_count: number;
  created_at: string; // ISO timestamp
  summary: string; // 2-3 paragraph narrative summary of style DNA
}

// =====================================================
// Feature 19: AI Fashion Designer Types
// =====================================================

export type DesignCategory = 'top' | 'bottom' | 'shoes' | 'outerwear' | 'dress' | 'accessory';

export type DesignStyle =
  | 'casual'
  | 'formal'
  | 'elegant'
  | 'sporty'
  | 'bohemian'
  | 'minimalist'
  | 'edgy'
  | 'vintage'
  | 'romantic'
  | 'streetwear';

export interface AIDesignRequest {
  description: string; // User's text description of desired item
  category: DesignCategory;
  style?: DesignStyle; // Optional style hint
  color_preferences?: string[]; // Optional color hints
  occasion?: string; // Optional occasion (e.g., "work", "party")
}

export interface AIDesignedItem {
  id: string;
  request: AIDesignRequest;
  image_url: string; // Generated image from Imagen 4
  optimized_prompt: string; // AI-enhanced prompt used for generation
  metadata: ClothingItemMetadata; // Auto-analyzed metadata from generated image
  created_at: string; // ISO timestamp
  added_to_closet: boolean; // Whether user added it to their closet
  in_wishlist: boolean; // Whether user saved it to wishlist
}

export interface DesignGallery {
  designs: AIDesignedItem[];
  total_designs: number;
  last_updated: string;
}

// ===========================
// Style Evolution Timeline
// ===========================

export type TrendType = 'color_shift' | 'category_preference' | 'style_evolution' | 'spending_pattern' | 'seasonality' | 'brand_preference';
export type TrendDirection = 'increasing' | 'decreasing' | 'stable' | 'fluctuating';
export type MilestoneType = 'first_item' | 'wardrobe_expansion' | 'style_shift' | 'color_discovery' | 'category_diversification' | 'investment_piece';

export interface StyleEvolutionPeriod {
  period_name: string; // "Early Days", "Mid 2024", "Recent Months"
  date_range: string; // "Jan 2024 - Mar 2024"
  item_count: number;
  dominant_colors: string[]; // Top 3 colors
  dominant_categories: string[]; // Top 3 categories
  dominant_styles: string[]; // Top 3 vibe_tags
  average_price_range?: string; // "budget", "mid-range", "premium"
  key_characteristics: string; // 2-3 sentence summary
}

export interface StyleTrend {
  trend_type: TrendType;
  title: string; // "Shifting to Neutrals", "More Minimalist"
  direction: TrendDirection;
  confidence: number; // 0-100
  description: string; // 2-3 sentences explaining the trend
  evidence: string[]; // 3-5 specific data points
  visualization_data?: {
    labels: string[];
    values: number[];
  };
}

export interface StyleMilestone {
  id: string;
  milestone_type: MilestoneType;
  date: string; // ISO date
  title: string; // "First Designer Piece"
  description: string; // Context and significance
  related_item_ids?: string[]; // Optional item references
  icon: string; // Material icon name
}

export interface StylePrediction {
  prediction: string; // "You'll likely continue embracing minimalism"
  confidence: number; // 0-100
  reasoning: string; // 2-3 sentences explaining why
  recommendations: string[]; // 3-5 actionable suggestions
  timeline: string; // "Next 3-6 months"
}

export interface StyleEvolutionTimeline {
  id: string;
  user_id?: string;
  periods: StyleEvolutionPeriod[]; // 3-5 periods chronologically
  trends: StyleTrend[]; // 4-6 major trends
  milestones: StyleMilestone[]; // 5-10 key milestones
  predictions: StylePrediction[]; // 2-3 future predictions
  overall_journey_summary: string; // 3-4 paragraph narrative
  confidence_level: 'low' | 'medium' | 'high'; // Based on data quantity
  analyzed_items_count: number;
  date_range: string; // "Jan 2024 - Jan 2025"
  created_at: string;
}

// ===========================================
// GOOGLE CALENDAR SYNC TYPES (Feature 9)
// ===========================================

export type CalendarEventType =
  | 'work_meeting' // Reuniones de trabajo
  | 'presentation' // Presentaciones formales
  | 'dinner_date' // Cena romántica
  | 'casual_hangout' // Salida casual con amigos
  | 'interview' // Entrevista laboral
  | 'party' // Fiesta o evento social
  | 'workout' // Ejercicio o actividad física
  | 'travel' // Viaje o transporte
  | 'formal_event' // Evento formal
  | 'other'; // Otro tipo de evento

export interface GoogleCalendarEvent {
  id: string; // Google Calendar event ID
  summary: string; // Event title
  description?: string; // Event description
  start: string; // ISO 8601 datetime
  end: string; // ISO 8601 datetime
  location?: string; // Event location
  event_type?: CalendarEventType; // AI-inferred event type
}

export interface OutfitSuggestionForEvent {
  event_id: string; // References GoogleCalendarEvent.id
  event_summary: string; // For display
  event_date: string; // ISO 8601 datetime
  event_type: CalendarEventType;
  suggested_outfit: FitResult; // Reuses existing FitResult type
  reasoning: string; // Why this outfit works for this event
  dress_code_analysis?: string; // Extracted from event description
  confidence: number; // 0-100
}

export interface GoogleCalendarConnection {
  is_connected: boolean;
  user_email?: string; // Google account email
  access_token?: string; // OAuth access token
  refresh_token?: string; // OAuth refresh token
  token_expiry?: string; // ISO 8601 datetime
  last_sync?: string; // ISO 8601 datetime of last successful sync
}

// ===== ACTIVITY FEED TYPES =====
// Friend Activity Feed - Social feature for discovering community content

export type ActivityType =
  | 'outfit_shared'          // User shared a new outfit
  | 'item_added'             // User added a clothing item
  | 'challenge_completed'    // User completed a style challenge
  | 'outfit_saved'           // User saved an outfit to favorites
  | 'capsule_created'        // User created a capsule wardrobe
  | 'style_milestone'        // User achieved a style milestone
  | 'lookbook_created'       // User created a lookbook
  | 'rating_given';          // User rated an outfit

export interface ActivityFeedItem {
  id: string;                           // Unique activity ID (timestamp-based)
  user_id: string;                      // ID of user who performed action
  user_name: string;                    // Display name of user
  user_avatar?: string;                 // Avatar URL or data URL
  activity_type: ActivityType;          // Type of activity
  timestamp: string;                    // ISO 8601 datetime

  // Activity-specific content (only one populated based on activity_type)
  outfit?: SavedOutfit;                 // For outfit_shared, outfit_saved
  clothing_item?: ClothingItem;         // For item_added
  challenge?: StyleChallenge;           // For challenge_completed
  capsule?: CapsuleWardrobe;            // For capsule_created
  lookbook?: Lookbook;                  // For lookbook_created
  outfit_rating?: OutfitRating;         // For rating_given

  // User-generated content
  caption?: string;                     // Optional caption/description
  tags?: string[];                      // Optional tags (#casual, #formal, etc.)

  // Engagement metrics (denormalized for performance)
  likes_count: number;                  // Total likes
  comments_count: number;               // Total comments
  shares_count: number;                 // Total shares

  // Current user interaction state
  is_liked: boolean;                    // Has current user liked this?
  is_shared: boolean;                   // Has current user shared this?
}

export interface ActivityComment {
  id: string;                           // Unique comment ID
  activity_id: string;                  // References ActivityFeedItem.id
  user_id: string;                      // ID of commenter
  user_name: string;                    // Display name of commenter
  user_avatar?: string;                 // Avatar of commenter
  content: string;                      // Comment text
  timestamp: string;                    // ISO 8601 datetime
  likes_count?: number;                 // Optional: comment likes
}

export interface ActivityEngagement {
  activity_id: string;                  // References ActivityFeedItem.id
  user_id: string;                      // User who performed engagement
  engagement_type: 'like' | 'comment' | 'share';
  timestamp: string;                    // ISO 8601 datetime
}

// Activity filter options for feed customization
export type ActivityFilterOption = 'all' | ActivityType;

export interface ActivityFeedFilters {
  types: ActivityFilterOption[];        // Filter by activity types
  users?: string[];                     // Filter by specific users (friend IDs)
  date_range?: {
    start: string;                      // ISO 8601 datetime
    end: string;                        // ISO 8601 datetime
  };
}

// =====================================================
// Feature 23: Virtual Shopping Assistant Types
// =====================================================

export type ShopName = 'Zara' | 'H&M' | 'Uniqlo' | 'COS' | 'Mango' | 'Pull&Bear' | 'Bershka' | 'Stradivarius' | 'Forever 21' | 'Reserved';

export interface ShoppingProduct {
  id: string;                           // Unique product ID
  title: string;                        // Product name (e.g., "Camisa Oxford Blanca")
  brand: ShopName;                      // Brand/Store name
  price: number;                        // Price in ARS
  currency: string;                     // "ARS"
  image_url: string;                    // Product image URL
  shop_url: string;                     // Link to product page (mock)
  category: string;                     // "top", "bottom", "shoes", etc.
  subcategory: string;                  // Specific item type
  color_primary: string;                // Primary color
  sizes_available: string[];            // Available sizes (e.g., ["XS", "S", "M", "L"])
  in_stock: boolean;                    // Stock status
  similarity_to_gap: number;            // 0-100, relevance to identified gap
  match_reasoning: string;              // Why this product fills the gap
  estimated_quality: 'budget' | 'mid-range' | 'premium'; // Quality tier based on price/brand
}

export interface ShoppingGap {
  id: string;                           // Unique gap ID
  category: string;                     // e.g., "top", "bottom", "shoes"
  subcategory: string;                  // e.g., "white button-down shirt"
  color_suggestion: string;             // Recommended color
  priority: 'essential' | 'recommended' | 'optional';
  reasoning: string;                    // Why this gap exists
  occasions: string[];                  // Use cases (e.g., ["work", "formal"])
  estimated_budget: string;             // Price range (e.g., "AR$ 10,000 - 20,000")
  alternatives?: string[];              // Similar items to consider
  current_inventory_count: number;      // How many similar items user already has
  versatility_impact: number;           // 0-100, how much this would improve wardrobe
}

export interface ShoppingRecommendation {
  gap: ShoppingGap;                     // The gap being addressed
  products: ShoppingProduct[];          // Recommended products to fill this gap
  total_budget_estimate: number;        // Total cost for all recommended products
  priority_order: number;               // 1-N, order of importance
  strategy_note: string;                // AI explanation of recommendation strategy
}

export interface PriceAlert {
  id: string;                           // Unique alert ID
  product_id: string;                   // References ShoppingProduct.id
  product_title: string;                // For display
  current_price: number;                // Current price
  target_price: number;                 // User's desired price
  discount_percentage: number;          // Current discount %
  is_active: boolean;                   // Whether alert is active
  created_at: string;                   // ISO 8601 datetime
  triggered_at?: string;                // When alert was triggered
  expires_at?: string;                  // When alert expires
}

export type ShoppingChatRole = 'user' | 'assistant' | 'system';

export interface ShoppingChatMessage {
  id: string;                           // Unique message ID
  role: ShoppingChatRole;               // Who sent the message
  content: string;                      // Message text
  timestamp: string;                    // ISO 8601 datetime

  // Optional structured data
  products?: ShoppingProduct[];         // Product suggestions in message
  gap_analysis?: ShoppingGap[];         // Gap analysis results
  recommendations?: ShoppingRecommendation[]; // Strategic recommendations
  action_buttons?: ShoppingChatAction[]; // Quick action buttons
}

export interface ShoppingChatAction {
  id: string;                           // Unique action ID
  label: string;                        // Button text (e.g., "Ver productos")
  action_type: 'view_products' | 'analyze_gaps' | 'create_alert' | 'search_specific' | 'compare_prices';
  payload?: any;                        // Action-specific data
}

export interface ShoppingConversationState {
  messages: ShoppingChatMessage[];      // Chat history
  is_typing: boolean;                   // Is AI typing?
  current_gaps?: ShoppingGap[];         // Currently identified gaps
  current_recommendations?: ShoppingRecommendation[]; // Current recommendations
  price_alerts: PriceAlert[];           // Active price alerts
  shopping_cart: ShoppingProduct[];     // Items user is considering
  total_budget_used: number;            // Sum of cart prices
}

// ===========================================
// MULTIPLAYER CHALLENGES TYPES (Feature 22)
// ===========================================

export type ChallengeType =
  | 'style_theme'         // Specific style (e.g., "minimalist", "bohemian")
  | 'color_challenge'     // Use specific colors
  | 'budget_limit'        // Create outfit under budget
  | 'category_specific'   // Use specific categories (e.g., only vintage)
  | 'seasonal'            // Season-appropriate outfit
  | 'occasion'            // Specific occasion (e.g., wedding, interview)
  | 'mix_match'           // Combine incompatible items
  | 'monochrome'          // Single color outfit
  | 'pattern_mix'         // Mix patterns creatively
  | 'trend_recreation';   // Recreate a trend

export type ChallengeStatus =
  | 'pending'    // Created, waiting for participants
  | 'active'     // Participants joining and submitting
  | 'voting'     // Voting phase
  | 'completed'  // Winner determined
  | 'expired';   // Ended without completion

export type ChallengeDifficulty = 'easy' | 'medium' | 'hard';

export interface MultiplayerChallenge {
  id: string;                           // Unique challenge ID
  creator_id: string;                   // User who created the challenge
  creator_name: string;                 // Display name
  creator_avatar?: string;              // Avatar URL

  // Challenge details
  title: string;                        // Challenge name
  description: string;                  // Challenge rules and requirements
  challenge_type: ChallengeType;        // Type of challenge
  difficulty: ChallengeDifficulty;      // Easy/medium/hard
  requirements: string[];               // Specific requirements (e.g., ["Include black", "Max 3 items"])

  // Timing
  created_at: string;                   // ISO 8601
  start_time: string;                   // When challenge becomes active
  end_time: string;                     // Submission deadline
  voting_end_time: string;              // Voting deadline
  status: ChallengeStatus;

  // Participation
  max_participants?: number;            // Optional limit
  participant_ids: string[];            // User IDs who joined
  participant_count: number;            // Current count
  submission_count: number;             // Submitted outfits

  // Scoring
  points_reward: number;                // Points for winner
  participation_points: number;         // Points for participating

  // Visibility
  is_public: boolean;                   // Public or friend-only
  tags?: string[];                      // Search tags
}

export interface ChallengeSubmission {
  id: string;                           // Unique submission ID
  challenge_id: string;                 // References MultiplayerChallenge.id
  user_id: string;                      // Participant ID
  user_name: string;                    // Display name
  user_avatar?: string;                 // Avatar URL

  // Outfit details
  top_id: string;                       // ClothingItem ID
  bottom_id: string;                    // ClothingItem ID
  shoes_id: string;                     // ClothingItem ID
  accessories_ids?: string[];           // Optional accessories

  // Submission metadata
  caption?: string;                     // User's explanation
  submitted_at: string;                 // ISO 8601

  // Voting
  votes_count: number;                  // Total votes received
  voters: string[];                     // User IDs who voted
  score: number;                        // Calculated score (votes + judge bonus)
  is_winner: boolean;                   // Winner flag
  winner_badge?: string;                // "🥇", "🥈", "🥉"
}

export interface ChallengeVote {
  id: string;                           // Unique vote ID
  challenge_id: string;                 // References challenge
  submission_id: string;                // Which submission
  voter_id: string;                     // Who voted
  voted_at: string;                     // ISO 8601
  comment?: string;                     // Optional feedback
}

export interface ChallengeLeaderboardEntry {
  rank: number;                         // 1, 2, 3...
  user_id: string;                      // User ID
  user_name: string;                    // Display name
  user_avatar?: string;                 // Avatar URL

  // Stats
  total_points: number;                 // All-time points
  challenges_won: number;               // 1st place finishes
  challenges_participated: number;      // Total challenges
  win_rate: number;                     // Win percentage (0-100)
  submissions_count: number;            // Total submissions
  votes_received: number;               // Total votes across all challenges

  // Achievements
  achievement_badges: ChallengeAchievement[]; // Unlocked achievements
  current_streak: number;               // Consecutive challenges
  best_streak: number;                  // Record streak
}

export interface ChallengeAchievement {
  id: string;                           // Unique achievement ID
  name: string;                         // Achievement name
  description: string;                  // How to unlock
  icon: string;                         // Material icon or emoji
  badge_color: string;                  // Tailwind color class
  points_value: number;                 // Points awarded
  unlocked_at?: string;                 // ISO 8601 (if unlocked)
  progress?: number;                    // 0-100 (for partial progress)
  requirement: number;                  // Total needed to unlock
}

export interface ChallengeNotification {
  id: string;                           // Unique notification ID
  user_id: string;                      // Recipient
  challenge_id: string;                 // Related challenge
  notification_type:
    | 'challenge_invite'                // Invited to challenge
    | 'voting_started'                  // Voting phase began
    | 'challenge_won'                   // You won!
    | 'new_submission'                  // Someone submitted
    | 'challenge_ending_soon'           // 1 hour before deadline
    | 'achievement_unlocked';           // New achievement
  message: string;                      // Notification text
  created_at: string;                   // ISO 8601
  is_read: boolean;                     // Read status
  action_url?: string;                  // Link to challenge
}

// =====================================================
// Professional Stylist System Types
// =====================================================

// Morfología corporal (5 tipos base)
export type BodyShape =
  | 'triangulo'            // Cadera > Hombros (pera)
  | 'triangulo_invertido'  // Hombros > Cadera
  | 'rectangulo'           // Hombros ≈ Cadera, sin cintura definida
  | 'reloj_arena'          // Hombros ≈ Cadera, cintura marcada
  | 'oval';                // Sin definición de cintura

// Paletas estacionales (sistema 12 estaciones)
export type ColorSeason =
  | 'primavera_clara'      // Light Spring
  | 'primavera_brillante'  // Bright Spring
  | 'primavera_calida'     // Warm Spring
  | 'verano_claro'         // Light Summer
  | 'verano_suave'         // Soft Summer
  | 'verano_frio'          // Cool Summer
  | 'otoño_suave'          // Soft Autumn
  | 'otoño_calido'         // Warm Autumn
  | 'otoño_profundo'       // Deep Autumn
  | 'invierno_profundo'    // Deep Winter
  | 'invierno_frio'        // Cool Winter
  | 'invierno_brillante';  // Bright Winter

// Nivel de contraste (piel vs pelo)
export type ContrastLevel = 'alto' | 'medio' | 'bajo';

// Preferencias de fit por categoría
export interface FitPreferences {
  tops: 'fitted' | 'relaxed' | 'structured' | 'oversized';
  bottoms: 'fitted' | 'relaxed' | 'wide-leg';
  dresses: 'fitted' | 'relaxed' | 'structured' | 'oversized';
}

// Perfil de morfología
export interface MorphologyProfile {
  body_shape: BodyShape;
  fit_preferences: FitPreferences;
  height_cm?: number;
  has_accessibility_needs?: boolean;
}

// Perfil de colorimetría personal
export interface ColorimetryProfile {
  color_season: ColorSeason;
  contrast_level: ContrastLevel;
  undertone?: 'cool' | 'warm' | 'neutral' | 'olive';
  skin_tone?: 'fair' | 'medium' | 'deep';
  recommended_palette?: string[]; // Hex colors
}

// Perfil de estilo de vida
export interface LifestyleProfile {
  primary_context: 'corporate' | 'creative' | 'casual' | 'mixed';
  climate_zone?: 'tropical' | 'temperate' | 'cold';
  budget_tier?: 'budget' | 'mid-range' | 'premium' | 'luxury';
  fabric_constraints?: string[]; // Alergias, sensibilidades
  maintenance_tolerance?: 'low' | 'medium' | 'high'; // Dry-clean vs lavable
}

// Perfil profesional completo
export interface ProfessionalProfile {
  id?: string;
  morphology: MorphologyProfile;
  colorimetry: ColorimetryProfile;
  preferences: {
    loves: string[]; // Tags o subcategorías que ama
    hates: string[]; // Tags o subcategorías que evita
  };
  lifestyle?: LifestyleProfile;
  completed_at?: string; // ISO timestamp
  profile_completeness_score?: number; // 0-100
}

// Resultado de outfit mejorado con explicaciones educativas
export interface ProfessionalFitResult extends FitResult {
  // Campos heredados de FitResult:
  // top_id, bottom_id, shoes_id, explanation, missing_piece_suggestion, aiGeneratedItems

  // Nuevos campos educativos
  educational?: {
    morphology_explanation: string;   // Por qué favorece tu cuerpo
    colorimetry_explanation: string;  // Por qué estos colores te quedan bien
    mood_explanation: string;         // Por qué encaja con la ocasión
  };

  // Metadata visual para UI
  ui_metadata?: {
    mood_color_hex: string;  // Color para orbes de fondo
    vibe: 'elegante' | 'casual' | 'sporty' | 'bohemian' | 'minimalist' | 'edgy' | 'romantic';
    formality_level: number; // 1-5
  };

  // Nombres descriptivos para mostrar en UI
  item_names?: {
    top_name: string;
    bottom_name: string;
    shoes_name: string;
    accessories_name?: string;
  };
}

// Export payment and subscription types
export * from './types-payment';
