/**
 * IndexedDB Wrapper for AI Generation Queue Persistence
 * 
 * Replaces localStorage for the AIGenerationContext to avoid QuotaExceededError
 * when saving heavy base64 images generated by Virtual Try-On and AI requests.
 * 
 * Provides a simple Promise-based API for get, set, and clear.
 */

const DB_NAME = 'OjoDeLocaAIDB';
const STORE_NAME = 'aiGenerationQueue';
const DB_VERSION = 1;

let dbPromise: Promise<IDBDatabase> | null = null;

function getDB(): Promise<IDBDatabase> {
    if (dbPromise) return dbPromise;

    dbPromise = new Promise((resolve, reject) => {
        // Only available in browser environment
        if (typeof window === 'undefined' || !window.indexedDB) {
            reject(new Error('IndexedDB not supported in this environment'));
            return;
        }

        const request = window.indexedDB.open(DB_NAME, DB_VERSION);

        request.onerror = (event) => {
            console.error('Failed to open IndexedDB:', event);
            reject(new Error('IndexedDB open failed'));
        };

        request.onsuccess = (event) => {
            resolve((event.target as IDBOpenDBRequest).result);
        };

        request.onupgradeneeded = (event) => {
            const db = (event.target as IDBOpenDBRequest).result;
            if (!db.objectStoreNames.contains(STORE_NAME)) {
                db.createObjectStore(STORE_NAME);
            }
        };
    });

    return dbPromise;
}

export const aiStorage = {
    /**
     * Saves a value to IndexedDB
     * @param key The key to save under
     * @param val The value to save (objects are fine, native structured clone is used)
     */
    async set<T>(key: string, val: T): Promise<void> {
        try {
            const db = await getDB();
            return new Promise((resolve, reject) => {
                const tx = db.transaction(STORE_NAME, 'readwrite');
                const store = tx.objectStore(STORE_NAME);
                const req = store.put(val, key);

                req.onsuccess = () => resolve();
                req.onerror = () => reject(req.error);
            });
        } catch (err) {
            console.warn('aiStorage set failed, falling back to localStorage if small', err);
            // Fallback fallback if strictly necessary, but handled by caller mainly
        }
    },

    /**
     * Retrieves a value from IndexedDB
     * @param key The key to retrieve
     */
    async get<T>(key: string): Promise<T | undefined> {
        try {
            const db = await getDB();
            return new Promise((resolve, reject) => {
                const tx = db.transaction(STORE_NAME, 'readonly');
                const store = tx.objectStore(STORE_NAME);
                const req = store.get(key);

                req.onsuccess = () => resolve(req.result as T | undefined);
                req.onerror = () => reject(req.error);
            });
        } catch (err) {
            console.warn('aiStorage get failed', err);
            return undefined;
        }
    },

    /**
     * Removes a key from IndexedDB
     * @param key The key to remove
     */
    async remove(key: string): Promise<void> {
        try {
            const db = await getDB();
            return new Promise((resolve, reject) => {
                const tx = db.transaction(STORE_NAME, 'readwrite');
                const store = tx.objectStore(STORE_NAME);
                const req = store.delete(key);

                req.onsuccess = () => resolve();
                req.onerror = () => reject(req.error);
            });
        } catch (err) {
            console.warn('aiStorage remove failed', err);
        }
    },

    /**
     * Clears all AI data in the store
     */
    async clear(): Promise<void> {
        try {
            const db = await getDB();
            return new Promise((resolve, reject) => {
                const tx = db.transaction(STORE_NAME, 'readwrite');
                const store = tx.objectStore(STORE_NAME);
                const req = store.clear();

                req.onsuccess = () => resolve();
                req.onerror = () => reject(req.error);
            });
        } catch (err) {
            console.warn('aiStorage clear failed', err);
        }
    }
};
